### ISSUE TITLE
[bug] parameter description is incomplete if this parameter is optional and mandatory in different parameter set

### ISSUE THREAD

**Issue by BethanyZhou** [Azure/autorest.powershell#1127]
Taking parameter VaultName in Get-AzKeyVault for correct instance.
   **[[-VaultName] <String>]**
   [[-ResourceGroupName] <String>]
   [-Tag <Hashtable>]
   [-DefaultProfile <IAzureContextContainer>]
   [-SubscriptionId <String>]
   [<CommonParameters>]

Get-AzKeyVault
   **[-VaultName] <String>**
   [-Location] <String>
   [-InRemovedState]
   [-DefaultProfile <IAzureContextContainer>]
   [-SubscriptionId <String>]
   [<CommonParameters>]

### -VaultName
Specifies the name of the key vault.

```yaml
Type: System.String
Parameter Sets: GetVaultByName
Aliases: Name

Required: False
Position: 0
Default value: None
Accept pipeline input: True (ByPropertyName)
Accept wildcard characters: True
```

```yaml
Type: System.String
Parameter Sets: ByDeletedVault
Aliases: Name

Required: True
Position: 0
Default value: None
Accept pipeline input: True (ByPropertyName)
Accept wildcard characters: True

authorest.powershell makes parameter as True in all parameter sets.
