### ISSUE TITLE
Get-AzElasticTagRule has 2 ParameterSets with same Parameters

### ISSUE THREAD

**Issue by vidai-msft** [Azure/autorest.powershell#1189]
Using v4 to generate `Get-AzElasticTagRule` has same Parameters with different ParameterSets like below (Common parameters removed)
Cmdlet: Get-AzElasticTagRule
 -> ParameterSet: Get
   -> Parameter: MonitorName
   -> Parameter: ResourceGroupName
   -> Parameter: SubscriptionId
 -> ParameterSet: ListViaIdentityMonitor
   -> Parameter: MonitorInputObject
 -> ParameterSet: GetViaIdentityMonitor
   -> Parameter: MonitorInputObject

The swagger file is https://github.com/Azure/azure-rest-api-specs/blob/73d8ea03558929411b9f2e6be533e63409a2252c/specification/elastic/resource-manager/Microsoft.Elastic/stable/2023-06-01/elastic.json

**Comment by dolauli** [comment]
Just found the root cause of the issue. The parameter **RuleSetName** specific to one of the two parameter sets is hidden by following directive.

```
  - where:
      verb: Get|New
      subject: TagRule
      parameter-name: RuleSetName
    hide: true
    set:
      default:
        script: '"default"'
```

And in this case, you will need to add a directive to remove the parameter set as below.
<img width="314" alt="image" src="https://github.com/Azure/autorest.powershell/assets/11451757/1bbc1fc9-11c3-46db-a473-1383e5a231a9">
