### ISSUE TITLE
[Feature Request] Support Model Type Names with Namespace in `model-name`

### ISSUE THREAD

**Issue by peombwa** [Azure/autorest.powershell#1191]
Directives that use `model-name` to "filter a model" should also support model type names with namespaces. For example, we should be able to define a [table formatting directive](https://github.com/Azure/autorest.powershell/blob/main/docs/directives.md#table-formatting) that has "namespaced" type name to set the table format for a model type as shown below:
``` yml
directive:
  - where:
      model-name: Org.MyService.Namespace.TypeName
    set:
      format-table:
        properties:
          - DisplayName
          - Id
          - Mail
          - UserPrincipalName
```

**Comment by dolauli** [comment]
@peombwa There should be one namespace configured, why there are two different namespaces in your case.

**Comment by peombwa** [comment]
Per our existing architecture, we have a centrally managed [table formatting directive](https://github.com/Azure/autorest.powershell/blob/main/docs/directives.md#table-formatting) config that is shared across multiple modules (namespaces). The modules use the same types, so it made sense to manage the default format centrally. Each namespace/API version returns a different set of properties that we would like to differentiate by namespaces in our centrally managed table formatting directive config, hence the feature request:
``` yml
  - where:
      model-name: Org.MyService.v1.TypeName
    set:
      format-table:
        properties:
          - DisplayName
          - Id
          - Mail
          - UserPrincipalName
  - where:
      model-name: Org.MyService.beta.TypeName
    set:
      format-table:
        properties:
          - DisplayName
          - Id
          - Mail
          - UserType
```

I'm aware that we can look at splitting the directive config into each module, but this will lead to duplication of directives since we have several modules.
