### ISSUE TITLE
Parameter default value from configuration

### ISSUE THREAD

**Issue by NelsonDaniel** [Azure/autorest.powershell#129]

**Comment by MiYanni** [comment]
- Add `DefaultInfoAttribute` (that is basically a copy/paste of the `CompleterInfoAttribute`)
- Allow this attribute to be decorated onto the generated cmdlets from configuration
  - Something akin to:
```
  - where:
      parameter-name: SubscriptionId
    set:
      default:
        script: '{ (Get-AzContext).Subscription.Id }'
```
  - This is similar to how a completer is set (just replace `default` with `completer`)
- Update exports to read `DefaultInfoAttribute` and process it
  - Would update the exported `begin` logic to check the parameter set and check if the parameter is already in PSBoundParameters. Then, set it if it isn't there.
  - Would need to always set that parameter to non-mandatory in that parameter set
