### ISSUE TITLE
[Feature] Generate cmdlet to Add/remove elements from a complex array parameter

### ISSUE THREAD

**Issue by dolauli** [Azure/autorest.powershell#1300]
Following a valid user case from the user side.

Let's say we have the cmdlet as below.

```
New-AzResourceA [-network <Network[]>] -Name <string> ...
```

Users may need to update the network by adding/removing elements from the network configuration in ResourceA.

So it is better We could generate two cmdlets like add-AzResourceANetwork, remove-AzResourceANetwork to support this scenario.

**Comment by isra-fel** [comment]
We can even expand the scope to not only complex objects, but also primitive types.
Also, since enabling this will introduce a lot of new cmdlets, we should probably design it to be a property level directive. For example:

```yaml
directives:
    - where:
        - cmdlet: New-AzResource
        - parameter: Network
    - set:
        - collection-extra-cmdlets: true
```
