### ISSUE TITLE
Default parameter set from config

### ISSUE THREAD

**Issue by NelsonDaniel** [Azure/autorest.powershell#133]

**Comment by cormacpayne** [comment]
@fearthecowboy 👀

**Comment by fearthecowboy** [comment]
add config to support adding a default parameter set name to a generated cmdlet (which would then propogate to the exported cmdlet)
example config 
``` 
directive: 
  where:
   variant:  CreateExpanded 
  set:
    defaultParameterSet: true
```
