### ISSUE TITLE
metadata override in README.md is being ignored

### ISSUE THREAD

**Issue by papadeltasierra** [Azure/autorest.powershell#1397]
Ref: docs/metadata.md

I am working for XML that looks like this:
``` yaml
require:
  - some/path/to/file.md

metadata:
  authors: The Author I Want
```
The file `/some/path/to/file.md` contains the following:

```
> Values
`````` yaml
metadata:
  authors: Some other Author
```

I am finding that my attempt to override the `author` is being ignored - is this expected?  Is there any way to make my override take affect?
