### ISSUE TITLE
Add completers to known properties

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/autorest.powershell#141]
SubscriptionID, ResourceGroup, Location

**Comment by markcowl** [comment]
I think the right thing is for us to model the correct internal hidden generated resourcemanager cmdlets to support this, and model the completer code using these models, and then we can look at the best way to include these in the generated code

**Comment by fearthecowboy** [comment]
I've been looking at this; I think we're going to need to adjust the delegates to the AzAccount  module.

Because of when the Completer gets called in  PowerShell, I don't have an InvocationInfo yet, (or an actual instance of the cmdlet, really).

currently:
``` 
public string[] CompleteArgument(string completerName, InvocationInfo invocationInfo, string correlationId, string[] resourceTypes, string[] parentResourceParameterNames)

```
has to change to 
``` 
public string[] CompleteArgument(string completerName, Dictionary fakeBoundParameters, string[] resourceTypes, string[] parentResourceParameterNames)
// I have no correlationId  nor InfocationInfo

```

I think I can still pull thru `resourceTypes` and `parentResourceParameterNames` -- since I'm generating the `ICompleter`, in the same class as the cmdlet itself, I have access to that data.  

Still may be a bit tricky to match them correctly, since I have to tear apart the operation URI, ignore `subscriptionid`/`resourcegroupname` and turn the remaining path parameters into `resourceTypes` and `parentResourceParameterNames` ... greasy work 😨 

Still, I think it's doable. Lemme see if I can get one going and tweak AzAccounts, and then send @markcowl  a PR for that.

**Comment by fearthecowboy** [comment]
I've added a support for a directive to set the completer info for a powershell cmdlet parameter.

This allows us to set the `ArgumentCompleterAttribute` for a given virtual parameter. 

``` yaml
- where:
    parameter-name: SubscriptionId
  set:
    completer: 
      name: SubscriptionCompleter
      description: gets the available subscriptions from the account services
      script: invoke-aztabcomplete @args   
      # that would make the cmdlet call `invoke-aztabcomplete` with standard IArgumentCompleter arguments 
```

We can use this to make things complete the way we want to in the exported layer.
