### ISSUE TITLE
Parameter Min/Max

### ISSUE THREAD

**Issue by dicolanl** [Azure/autorest.powershell#1461]
We have a parameter in openapi
```yaml
limitParameter:
      name: _limit
      in: query
      description: Limit the return results
      required: true
      schema:
        type: integer
        default: 30
        maximum: 400
        minimum: 1
```

but in docs that are generated it doesnt say min or max.

### -Limit
Limit the return results

```yaml
Type: System.Int32
Parameter Sets: List
Aliases:

Required: False
Position: Named
Default value: 30
Accept pipeline input: False
Accept wildcard characters: False
```

Is there a way to have autorest pass these to the docs?  
default was passed using a directive, but maybe the geneartor can just inherit from the openapi spec the default too?
