### ISSUE TITLE
Resources with capitalization differences cause Deduplicator failures

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest.powershell#182]
This appears to happen for any generation of compute using the latest profile with the hybrid profile.

It appears to be because some vitualMachineScaleSets resources use different capitalization between API Versions
 for example, in this file: https://github.com/NelsonDaniel/azure-rest-api-specs/blob/multiapi/profiles/stable-2019-01.md 
```yaml
'2017-12-01':
  - virtualmachineScaleSets/networkInterfaces
'2017-03-30':
  - virtualMachineScaleSets/networkInterfaces
```

The failure stack is:

```
PS C:\td\azure-powershell\src\Compute> autorest
AutoRest code generation utility [version: 3.0.5163; node: v10.15.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5399\node_modules\@microsoft.azure\autorest-core\dist' (3.0.5399)
   Loading AutoRest extension '@microsoft.azure/autorest.powershell' (beta->1.0.329)
   Loading AutoRest extension '@microsoft.azure/autorest.remodeler' (beta->1.0.203)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp-v2' (beta->1.0.216)
C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5399\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Deduplicator: There's a conflict in profile data. There should be a single path api-version per profile. / Error: Deduplicator: There's a conflict in profile data. There should be a single path api-version per profile.
    at getMergedProfilesMetadata (/node_modules/@microsoft.azure/deduplication/dist/main.js:352:19)
    at Deduplicator.deduplicatePaths (/node_modules/@microsoft.azure/deduplication/dist/main.js:148:40)
    at Deduplicator.init (/node_modules/@microsoft.azure/deduplication/dist/main.js:77:26)
    at Deduplicator.get output [as output] (/node_modules/@microsoft.azure/deduplication/dist/main.js:331:18)
    at deduplicate (C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5399\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\deduplicator.js:15:82)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  Error: Deduplicator: There's a conflict in profile data. There should be a single path api-version per profile.
```

**Comment by markcowl** [comment]
Note that even if the duplicated lines between api-versions within a profile are removed, the issue occurs.  I assume this is because of capitalization differences between the api-versions.

Here is a readme file that duplicates the issue:
```yaml
# AutoRest Configuration for Compute

> see https://aka.ms/autorest

``` yaml
require: 
  - $(this-folder)/../readme.azure.md
  - https://raw.githubusercontent.com/markcowl/azure-rest-api-specs/multi-api/specification/compute/resource-manager/readme.enable-multi-api.md
  - https://raw.githubusercontent.com/markcowl/azure-rest-api-specs/blob/multi-api/specification/compute/resource-manager/readme.md

service-name: Compute
subject-prefix: ''
module-version: 0.0.1
skip-model-cmdlets: true
profile: 
  - 2019-03-01-hybrid
  - 2019-04-01-profile
  - stable-2019-01
  - latest
directive: 
  - where:
      noun: VirtualMachineScaleSet(.*)
    set:
      noun: Vmss$1
  - where:
      noun: VirtualMachine(.*)
    set:
      noun: VM$1
  - where:
      noun: VM
      parameter-name: VmName
    set:
      parameter-name: Name
```


With readme.azure.json looking like this:

```yaml
# Azure PowerShell AutoRest Configuration

> Language
``` yaml
use:
- "@microsoft.azure/autorest.powershell@beta"

```

> Values
``` yaml
azure: true
enable-multi-api: true
```

> Names
``` yaml
prefix: Az
subject-prefix: $(service-name)
module-name: $(prefix).$(service-name)
namespace: Microsoft.Azure.PowerShell.Cmdlets.$(service-name)
```

> Folders
``` yaml
clear-output-folder: true
output-folder: $(service-name)
```

> Directives
``` yaml
directive:
  - where:
      subject: Operation
    set:
      hidden: true
```
```
