### ISSUE TITLE
Events creating conflict present in PSCmdlet.Events and NewMicrosoftGraphGroupObject

### ISSUE THREAD

**Issue by NakulSabharwal** [Azure/autorest.powershell#187]
When I generate and build the attached openapi file then I get the following error because of conflicting name of Events in NewMicrosoftGraphGroupObject and parent class.

[openapi-groups.zip](https://github.com/Azure/autorest.powershell/files/3047467/openapi-groups.zip)

```
generated\model-cmdlets\NewMicrosoftGraphGroupObject.cs(199,57): error CS0108: 'NewMicrosoftGraphGroupObject.Events' hides inherited member 'PSCmdlet.Events'. Use the new keyword if hiding was intended. [C:\Users\nasabhar\Desktop\power\groups\generated\$(title).csproj]
generated\cmdlets\InvokeGroupGroupCreateGroup_GroupCreateGroupIdDeletedDateTimeDescriptionAcceptedSendersAllowEtc.cs(219,57): error CS0108: 'InvokeGroupGroupCreateGroup_GroupCreateGroupIdDeletedDateTimeDescriptionAcceptedSendersAllowEtc.Events' hides inherited member 'PSCmdlet.Events'. Use the new keyword if hiding was intended. [C:\Users\nasabhar\Desktop\power\groups\generated\$(title).csproj]
generated\cmdlets\InvokeGroupGroupUpdateGroup_GroupUpdateGroupGroupIdDeletedDateTimeDescriptionAcceptedSendersEtc.cs(219,57): error CS0108: 'InvokeGroupGroupUpdateGroup_GroupUpdateGroupGroupIdDeletedDateTimeDescriptionAcceptedSendersEtc.Events' hides inherited member 'PSCmdlet.Events'. Use the new keyword if hiding was intended. [C:\Users\nasabhar\Desktop\power\groups\generated\$(title).csproj]
C:\Users\nasabhar\Desktop\power\groups\generated\build-module.ps1 : Compilation failed.
At C:\Users\nasabhar\Desktop\power\groups\generated\build-module.ps1:70 char:3
+   Write-Error 'Compilation failed.'
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,build-module.ps1
```

**Comment by fearthecowboy** [comment]
Should be de-pluralizing  `events` to `event`

**Comment by fearthecowboy** [comment]
So, you have to create a configuration file

See documentation: 
 - https://github.com/Azure/autorest/blob/master/docs/user/configuration.md
 - https://github.com/Azure/autorest/blob/master/docs/powershell/options.md

Place the following in a file called `readme.md` , and then just run `autorest readme.md`

> `readme.md` 

~~~ markdown
# Configuration File for generating powershell cmdlets for Graph

> see https://aka.ms/autorest 

``` yaml
# list your input files here
input-file: 
  - openapi-user.yml

# set powershell specific options here
powershell: 
  skip-model-cmdlets: true
  namespace: Microsoft.Graph
  
# tweak generated code here.
directive:
  - where: 
      property-name: Events
    set:  
      property-name: Event
```
~~~
