### ISSUE TITLE
Cannot generate storage module with multiple api-versions

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest.powershell#188]
Using this readme configuration: 
https://github.com/markcowl/azure-powershell/blob/generation/src/Storage/readme.md

The following error occurs:
```
PS C:\td\azure-powershell\src\Storage> autorest
AutoRest code generation utility [version: 3.0.5163; node: v10.15.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5399\node_modules\@microsoft.azure\autorest-core\dist' (3.0.5399)
   Loading AutoRest extension '@microsoft.azure/autorest.powershell' (beta->1.0.337)
   Loading AutoRest extension '@microsoft.azure/autorest.remodeler' (beta->1.0.207)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp-v2' (beta->1.0.220)
C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5399\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Deduplicator: There's a conflict in profile data. There should be a single path api-version per profile. / Error: Deduplicator: There's a conflict in profile data. There should be a single path api-version per profile.
    at getMergedProfilesMetadata (/node_modules/@microsoft.azure/deduplication/dist/main.js:352:19)
    at Deduplicator.deduplicatePaths (/node_modules/@microsoft.azure/deduplication/dist/main.js:148:40)
    at Deduplicator.init (/node_modules/@microsoft.azure/deduplication/dist/main.js:77:26)
    at Deduplicator.get output [as output] (/node_modules/@microsoft.azure/deduplication/dist/main.js:331:18)
    at deduplicate (C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5399\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\deduplicator.js:15:82)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  Error: Deduplicator: There's a conflict in profile data. There should be a single path api-version per profile.
```

**Comment by fearthecowboy** [comment]
fixed - works with `autorest.powershell@2.0.354`

**Comment by fearthecowboy** [comment]
( this require

**Comment by fearthecowboy** [comment]
The generated 'latest' profile by itself fails with this one..

~~~ markdown
# AutoRest Configuration for Storage

> see https://aka.ms/autorest

``` yaml
require: 
  - $(this-folder)/../readme.azure.md
  - https://raw.githubusercontent.com/azure/azure-rest-api-specs/multiapi/specification/storage/resource-manager/readme.enable-multi-api.md
  - https://raw.githubusercontent.com/azure/azure-rest-api-specs/multiapi/specification/storage/resource-manager/readme.md

service-name: Storage
subject-prefix: ''
title: StorageManagementClient
module-version: 0.0.1
skip-model-cmdlets: true
profile: 
  - latest-2019-04-01
```

output:
~~~

``` text
:\Users\garretts.NTDEV\.autorest\@microsoft.azure_autorest-core@3.0.5420\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Deduplicator: There's a conflict in profile data. There should be a single path api-version per profile. / Error: Deduplicator: There's a conflict in profile data. There should be a single path api-version per profile.
    at getMergedProfilesMetadata (/node_modules/@microsoft.azure/deduplication/dist/main.js:329:19)
    at Deduplicator.deduplicatePaths (/node_modules/@microsoft.azure/deduplication/dist/main.js:149:40)
    at Deduplicator.init (/node_modules/@microsoft.azure/deduplication/dist/main.js:78:26)
    at Deduplicator.get output [as output] (/node_modules/@microsoft.azure/deduplication/dist/main.js:308:18)
    at deduplicate (C:\Users\garretts.NTDEV\.autorest\@microsoft.azure_autorest-core@3.0.5420\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\deduplicator.js:15:82)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  Error: Deduplicator: There's a conflict in profile data. There should be a single path api-version per profile.
```
