### ISSUE TITLE
Add support for non-resource operations to Profile definition

### ISSUE THREAD

**Issue by fearthecowboy** [Azure/autorest.powershell#199]
Necessary for Resources, data-plane and tenant/subscription level operations

- Should only operate on paths that are *not* resources (ie, don't contain `/providers/` in path) 
- Should support regex wildcards
- Should support non-date level API versions.

~~~
```yaml
profiles:
  hybrid-2019:
   # Example non-resource paths:
   "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/" : 2016-09-01
   "/subscriptions/{subscriptionId}/resourceGroups/{sourceResourceGroupName}/.*": 2016-09-01
      
  
    microsoft.authorization:
      '2016-09-01':
        - locks
      '2016-12-01':
        - policyDefinitions
        - policyAssignments
```
~~~
