### ISSUE TITLE
Monitor building failing - Empty switch blocks

### ISSUE THREAD

**Issue by niander** [Azure/autorest.powershell#218]
Using the following configuration for Monitor module:

``` yaml
require:
  - $(this-folder)/../readme.azure.md
  - https://raw.githubusercontent.com/azure/azure-rest-api-specs/multiapi/specification/monitor/resource-manager/readme.enable-multi-api.md
  - https://raw.githubusercontent.com/azure/azure-rest-api-specs/multiapi/specification/monitor/resource-manager/readme.md
  - https://raw.githubusercontent.com/azure/azure-rest-api-specs/multiapi/specification/monitor/data-plane/readme.enable-multi-api.md
  - https://raw.githubusercontent.com/azure/azure-rest-api-specs/multiapi/specification/monitor/data-plane/readme.md

service-name: Monitor
subject-prefix: ''
module-version: 0.0.1
skip-model-cmdlets: true
profile:
  - hybrid-2019
  - latest-2019-04-01
```

During build I get the following errors:

```
generated\api\ModelsApi20180301\MetricAlertCriteria.json.cs(57,13): error CS1522: Empty switch block [C:\Users\niassis\source\repos\azure-powershell\src\Monitor\Monitor\Az.Monitor.csproj]
generated\api\ModelsApi20180416\Action.json.cs(72,13): error CS1522: Empty switch block [C:\Users\niassis\source\repos\azure-powershell\src\Monitor\Monitor\Az.Monitor.csproj]
generated\api\ModelsApi20160301\RuleCondition.json.cs(57,13): error CS1522: Empty switch block [C:\Users\niassis\source\repos\azure-powershell\src\Monitor\Monitor\Az.Monitor.csproj]
generated\api\ModelsApi20160301\RuleAction.json.cs(59,13): error CS1522: Empty switch block [C:\Users\niassis\source\repos\azure-powershell\src\Monitor\Monitor\Az.Monitor.csproj]
generated\api\ModelsApi20160301\RuleDataSource.json.cs(57,13): error CS1522: Empty switch block [C:\Users\niassis\source\repos\azure-powershell\src\Monitor\Monitor\Az.Monitor.csproj]
C:\Users\niassis\source\repos\azure-powershell\src\Monitor\Monitor\build-module.ps1 : Compilation failed.
At C:\Users\niassis\source\repos\azure-powershell\src\Monitor\Monitor\build-module.ps1:70 char:3
+   Write-Error 'Compilation failed.'
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,build-module.ps1
```

All of them are empty switch blocks being generated.
