### ISSUE TITLE
App Service Fails 

### ISSUE THREAD

**Issue by NelsonDaniel** [Azure/autorest.powershell#222]
PLUGIN FAILURE: Cannot read property 'value' of undefined, TypeError: Cannot read property 'value' of undefined
    at setOperationNames (C:\Users\xxxxx\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.235\node_modules\@microsoft.azure\autorest.csharp-v2\plugin-namer.ts:215:72)
    at nameStuffRight (C:\Users\xxxxx\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.235\node_modules\@microsoft.azure\autorest.csharp-v2\plugin-namer.ts:138:9), {}
FATAL: TypeError: Cannot read property 'value' of undefined

### Configuration readme.md

# AutoRest Configuration for AppService

> see https://aka.ms/autorest

``` yaml
require: 
  - $(this-folder)/../readme.azure.md
  - https://raw.githubusercontent.com/azure/azure-rest-api-specs/multiapi/specification/web/resource-manager/readme.enable-multi-api.md
  - https://raw.githubusercontent.com/azure/azure-rest-api-specs/multiapi/specification/web/resource-manager/readme.md

service-name: AppService
module-version: 0.0.1
skip-model-cmdlets: true
profile: 
  - hybrid-2019
  - latest-2019-04-01
```

### Configuration readme.azure.md

> Language
``` yaml
use:
- "@microsoft.azure/autorest.powershell@beta"


```

> Values
``` yaml
azure: true
enable-multi-api: true
```

> Names
``` yaml
prefix: Az
subject-prefix: $(service-name)
module-name: $(prefix).$(service-name)
namespace: Microsoft.Azure.PowerShell.Cmdlets.$(service-name)
```

> Folders
``` yaml
clear-output-folder: true
output-folder: $(service-name)
```

> Directives
``` yaml
directive:
  - where:
      subject: Operation
    set:
      hidden: true
```
