### ISSUE TITLE
Code Modifiers: Be able to select/scope explicitly by parameter, command, model, etc

### ISSUE THREAD

**Issue by NelsonDaniel** [Azure/autorest.powershell#230]
Example:
``` yaml
- select: command 
  where:
      subject: Foo
      parameter-name: Bar
  set:
      hidden: true
```
It selects all the commands that contain the subject Foo, contain the parameter Bar and hides them.
