### ISSUE TITLE
Alias cmdlets and parameters from configuration

### ISSUE THREAD

**Issue by NelsonDaniel** [Azure/autorest.powershell#244]
For parameters, for example:
``` yaml
where:
  parameter-name: Foo
set:
  alias: Bar
```

For Commands, for example:
``` yaml
where:
  verb: Get
  subject: Foo
set:
  alias: <any string>
```
This will require to modify the codemodel and add alias attributes to the low-level c# cmdlets. Also, export aliases: https://github.com/Azure/autorest.powershell/issues/120
