### ISSUE TITLE
Tags not being handled as Hashtable parameter

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.powershell#264]
```yaml
        "tags": {
          "description": "The ARM resource tags.",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
```
This becomes `Microsoft.Azure.PowerShell.Cmdlets.AppConfiguration.Models.Api20190201Preview.IConfigurationStoreUpdateParametersTags` for AppConfiguration. It should be a parameter of type `Hashtable`.
