### ISSUE TITLE
Empty classes be optimized out

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.powershell#265]
Basically, empty classes have no meaning.
```yaml
    "ConfigurationStorePropertiesUpdateParameters": {
      "description": "The properties for updating a configuration store.",
      "type": "object",
      "properties": {}
    }
```
If this isn't inherited, then it should be removed entirely. There's nothing to send to the API in this case.
