### ISSUE TITLE
Allow 'variant' for select directive

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.powershell#276]
If I want to remove every variant with a certain parameter, I should be able to specify:
```yaml
directive:
  - where:
      parameter-name: Parameter
    select: variant
    remove: true
```
And yes, the name of the parameter here is named `Parameter` (this is in ServiceBus).

**Comment by NelsonDaniel** [comment]
This is the behavior when doing:
```
directive:
  - where:
      parameter-name: Parameter
    select: command
    remove: true
```
If there is confusion about this we could change it to 

directive:
```
  - where:
      parameter-name: Parameter
    select: variant
    remove: true
```
