### ISSUE TITLE
Configuration, enum value rename doesn't work on enum named *

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.powershell#283]
For Network, they have an enum value named `*`. I attempted to use the configuration to rename it to a valid name (like `All`). But, it didn't work. Also, when I tried `''` as the name, it output this: `VERBOSE: [DIRECTIVE] Changed enum-name from SecurityRuleProtocol to SecurityRuleProtocol.`

I tried both of these:

```yaml
directive:
  - where:
      enum-name: SecurityRuleProtocol
      enum-value-name: '\*'
    set:
      enum-value-name: All
```
```yaml
directive:
  - where:
      enum-name: SecurityRuleProtocol
      enum-value-name: ''
    set:
      enum-value-name: All
```
