### ISSUE TITLE
Add support for adding an alias to multiple commands with a single directive

### ISSUE THREAD

**Issue by cormacpayne** [Azure/autorest.powershell#295]
Currently, it's only possible to set aliases for a single command with a single directive. In cases where we're adding aliases for backwards compatibility that follow the same pattern, this task becomes repetitive.

For example, when generating KeyVault cmdlets, the cmdlets in `Az.KeyVault` are called `*-*ManagedStorageAccount` and the cmdlets generated are called `*-*StorageAccount`. Rather than writing a directive per command, it would be nice to do something like the following:

```
- where:
      subject: StorageAccount
  set:
      alias: ${verb}-${prefix}${subject-prefix}Managed${subject}
```

This would also help in other cases, such as DataLakeStore, where they have an alias to `*-Adls*` for each of their cmdlets (to replace `*-AzDataLakeStore*`). This alias could then be easily set across all commands with the following directive:

```
- where:
      verb: .*
  set:
      alias: ${verb}-Adls${subject}
```
