### ISSUE TITLE
Incorrect URI format for nextLink when making calls to Graph

### ISSUE THREAD

**Issue by cormacpayne** [Azure/autorest.powershell#314]
This issue may apply to other data plane cmdlets, but in Graph, attempting to follow the `nextLink` on list calls results in an error when trying to convert the string to `System.Uri`. For example, when making a call using `Get-AzADUser`, the following line will throw the above error:

```cs
requestMessage = requestMessage.Clone(new global::System.Uri( result.OdataNextLink ),Microsoft.Azure.PowerShell.Cmdlets.Resources.Runtime.Method.Get );
```

The `result.OdataNextLink` string that's returned has the following value:

```
directoryObjects/$/Microsoft.DirectoryServices.User?$skiptoken=X'44537074020001000000163A5F6D7373616674406D6963726F736F66742E636F6D29557365725F30646434323738312D306231332D343434302D396331322D623630636139333037326234B900000000000000000000'
```

Looking at the [this call in Graph's SDK](https://github.com/Azure/azure-sdk-for-net/blob/36e9503c855ec20cbde3e96a2abd4180235e2963/src/SDKs/Graph.RBAC/Graph.RBAC/Generated/UsersOperations.cs#L1203), it appears they append this string to the end of `https://graph.windows.net/{{tenantId}}/`.

**Comment by fearthecowboy** [comment]
ME: do directive to allow us to call a function in a custom module.cs

**Comment by fearthecowboy** [comment]
Notes:

adding a `directive` to the configuration

``` yaml
directive:
  - from: source-file-csharp
    where: $                        
    transform: return $.replace( /(^\s*)(if\s*\(\s*result.NextLink\s*!=\s*null\s*\))/gm, '$1result.NextLink = Module.Instance.FixNextLink(result.NextLink);\n$1$2' );
```

will add a call to `Module.FixNextLink(string)` so you just have to implement the method in a custom Module class:

in `./custom/Module.cs`

``` csharp
namsepace Microsoft.Azure.PowerShell.Cmdlets.Resources
{
    public partial class Module 
    {
        public string FixNextLink( string nextlink ) 
        {
           if( !string.IsNullOrEmpty(nextlink) 
           {
              // modify the next link
              nextlink = $"https://somwehere.com/foo/{nextlink}";
           }
           return nextlink;
        }
    }
}
```
