### ISSUE TITLE
Cannot add aliases to InputObject parameter

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest.powershell#317]
For example, in the latest compute spec, the following directives result in no aliases:

``` yaml
  - where:
      verb: Remove
      subject: VmssExtension
      parameter-name: InputObject
    set:
      alias: VirtualMachineScaleSet

  - where:
      verb: Repair
      subject: VmssServiceFabricUpdateDomain
      parameter-name: InputObject
    set:
      alias: VirtualMachineScaleSet  
```
