### ISSUE TITLE
Allow regex from parameter-name to work in alias (for parameters)

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.powershell#351]
```yaml
  - where:
      parameter-name: (.*)VirtualNetwork(.*)
    set:
      alias: $1VirtualNetwork$2
```
Basically, I can set an alias for a parameter based on the name of the parameter.
