### ISSUE TITLE
Model property rename in configuration does not work

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest.powershell#353]
For example, single  property renames mentioning the model type:
```
- where:
      model-name: VirtualMachineSize
      property-name: ^NumberOfCore$
    set:
      property-name: NumberOfCores
  - where:
      model-name: VirtualMachineInstanceView
      property-name: ^MaintenanceRedeployStatus(.+)$
    set:
      property-name: $1
  - where:
      model-name: VirtualMachineInstanceView
      property-name: ^VMAgentVmagentVersion$
    set:
      property-name: VMAgentVersion
```
(this occurs whether the model name or interface name is used in `model-name`

Also, cross-model property configuration changes do not work:
```
 - where:
      property-name: ^CapacityDefaultCapacity$
    set:
      property-name: DefaultCapacity
  - where:
      property-name: ^Capacity(Default|Maximum|Minimum)$
    set:
      property-name: $1Capacity
  - where:
      property-name: ^RestrictionInfo(Location|Zone)$
    set:
      property-name: $1
```

(Note that this fails to change the property name
