### ISSUE TITLE
Allow regex from parameter-name selection to be used in aliases.

### ISSUE THREAD

**Issue by NelsonDaniel** [Azure/autorest.powershell#356]
Scenario:
```
where:
  parameter-name: (.*)VirtualMachine
set: 
  alias: $1VM
```
