### ISSUE TITLE
$(prefix) not working in directive

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.powershell#359]
```yaml
  - where:
      subject: (.*)VirtualNetwork(.*)
    set:
      alias: ${verb}-$(prefix)${subject-prefix}${subject}
```

Ends up making:
```powershell
[Alias('Get-$(prefix)VirtualNetworkGatewayConnection')]
```
