### ISSUE TITLE
No control over generated help link

### ISSUE THREAD

**Issue by Masus** [Azure/autorest.powershell#378]
Currently the url to the help documentation is hardcoded which prevent other organizations, outside Microsoft, to provide their own.

In a perfect world it would be great if the url format could be controlled but also hidden completely if not used (some times the inline help is enough). 

A first step could be to make it possible to at least provide a format for the link. One possible way of providing this capability could be to add an attribute to the metadata parameter (provided in the readme.md)

```
metadata:
  authors: <author>
  owners: <owner>
  ...
  moduleHelpUrlFormat: https://docs.microsoft.com/en-us/powershell/module/{moduleName}
  cmdLetHelpUrlFormat: https://docs.microsoft.com/en-us/powershell/module/{moduleName}/{cmdletName}
```
Another solution could be to provide a baseUrl and the rest is following a standard pattern (i.e always appending {module}/{cmdletName} etc.), simpler but less flexible.
