### ISSUE TITLE
Configuring cmdlet's table output

### ISSUE THREAD

**Issue by anton-evseev** [Azure/autorest.powershell#396]
Some `Network` cmdlets' output lacks important columns or has information that isn't not useful. I can fix that by adding another format file ([example](https://github.com/number213/azure-powershell/commit/a59d4cb8862f429d087e11e3cbe6fbfd779ff217)), but is there a way to configure cmdlet output through autorest?

---

Example 1: `Az-AzNetworkUsage` is missing column with resource type
```powershell
PS D:\azure-powershell\src\Network [Az.Network]> Get-AzNetworkUsage -Location westus                                                                                                                                                         
CurrentValue Limit      Unit
------------ -----      ----
12           1000       Count
1            1000       Count
1            5000       Count
```

Fixed version

```powershell
PS D:\azure-powershell\src\Network [Az.Network]> Get-AzNetworkUsage -Location westus                                                                                                                                                         
Resource Type                                                Current Value Limit      Unit
-------------                                                ------------- -----      ----
Virtual Networks                                             12            1000       Count
Static Public IP Addresses                                   1             1000       Count
Network Security Groups                                      1             5000       Count
```
---

Example 2: `Type` is the same for each resource and `Etag` isn't useful for table output. It could also use resource group name (there is no field like that, but it could be extracted from Id through script block)
```powershell
PS D:\azure-powershell\src\Network [Az.Network]> Get-AzVnet                                                                                                                                                                                  
Location      Name                        Type                              Etag
--------      ----                        ----                              ----
eastus        vnet1                       Microsoft.Network/virtualNetworks W/"59f5855e-9d6d-4e29-9c30-3d5e9f64317e"
eastus        vnet2                       Microsoft.Network/virtualNetworks W/"42ed9f85-a333-4a2b-a496-b23b21704156"
eastus        lb-vnet                     Microsoft.Network/virtualNetworks W/"7f8f8c49-a444-4309-b954-bd61f57faeef"
```

**Comment by MiYanni** [comment]
@number213 Yes. We have support for formatting changes. We haven't written the documentation for it yet, though. In `directive:`, it looks like this:
```yaml
  - where: 
      model-name: foo
  - set: 
      format-table:
        properties:
          - a
          - b
        labels:
          a: alabel
          b: blabel
        width: 
          a: 80
          b: 60
```

**Comment by number213** [comment]
@MiYanni 
I see that items in format.ps1xml are ordered alphabeticaly, but this leads to some not-that-significant properties being  first.

```
PS D:\az-gen\src\Resources [Az.Network]> Get-AzNatGateway -ResourceGroupName $rgname -Name $rname;

GUID                                 Name   Location SKU Name Provisioning State
----                                 ----   -------- -------- ------------------
7ded9119-36a0-43a3-9a74-6434eae67832 nat-gw eastus2  Standard Succeeded
```

```
PS D:\az-gen\src\Resources [Az.Network]>  Get-AzAvailableServiceDelegation -Location westus

Action                                                  Name
------                                                  ----
{Microsoft.Network/virtualNetworks/subnets/action}      Microsoft.Web.serverFarms
```

Can this order be configured? Or even better, can you take common properties (`Name`, `ResourceGroupName`) and put them first in ps1xml?

**Comment by MiYanni** [comment]
@number213 By default, the order of the properties is based on if they are Inherited or Owned. Inherited means they came from another class via composition. Owned means they are properties native to that object.
Now, this ordering was intentional. Meaning, I put it into configuration this way:
```yaml
  - where:
      model-name: ^LoadBalancer$|^NatGateway$
    set:
      format-table:
        properties:
          - ResourceGuid
          - Name
          - Location
          - SkuName
          - ProvisioningState
        labels:
          ResourceGuid: GUID
          SkuName: SKU Name
          ProvisioningState: Provisioning State
```

**Things to mention**: There are no 'common properties'. Meaning, there is no mechanism to determine what would be 'common' or not. Also note, since the object returned from the server does not have `ResourceGroupName`, it won't exist on any of the models. I put `ResourceGuid` there since we don't have a `ResourceGroupName`. It seemed like a somewhat significant value. At this point, everything that needs the order to be modified would have to have this information in directives in the readme.
