### ISSUE TITLE
Global rename of terms

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.powershell#418]
Instead of:
```yaml
  - where:
      subject: (.*)VirtualMachineScaleSet(.*)
    set:
      alias: ${verb}-Az${subject-prefix}${subject}
  - where:
      parameter-name: (.*)VirtualMachineScaleSet(.*)
    set:
      alias: $1VirtualMachineScaleSet$2
  - where:
      subject: (.*)VirtualMachineScaleSet(.*)
    set:
      subject: $1Vmss$2
  - where:
      parameter-name: (.*)VirtualMachineScaleSet(.*)
    set:
      parameter-name: $1Vmss$2
```
(which doesn't even cover property/class names) is needed to do some basic term renaming. Here: `VirtualMachineScaleSet -> Vmss`. We need global term renaming. This would be a configuration directive. It would rename a term anywhere, such as:
- Cmdlet names
- Parameter names
- Class names
- Property names

This would vastly simplify a lot of configuration.

**Comment by fearthecowboy** [comment]
If you're looking for doing a global, no-holds-barred transform:

``` yaml
directive:
  - from: source-file-csharp
    where: $
    transform: $.replace(/(.*)VirtualMachineScaleSet(.*)/g,"$1Vmss$2")
```

But I think you're right, we should have something that can handle that in a single go.

**Comment by fearthecowboy** [comment]
Curious: does this work?

``` yaml
- where:
      subject: (.*)VirtualMachineScaleSet(.*)
    set:
      alias: ${verb}-Az${subject-prefix}${subject}
      subject: $1Vmss$2
  - where:
      parameter-name: (.*)VirtualMachineScaleSet(.*)
    set:
      alias: $1VirtualMachineScaleSet$2
      parameter-name: $1Vmss$2
```
