### ISSUE TITLE
Allow support for optional -ApiVersion parameter with default value

### ISSUE THREAD

**Issue by cormacpayne** [Azure/autorest.powershell#433]
In some cases, such as generic ARM cmdlets, the API version defined in the spec of an operation isn't always the one that should be used. When creating, updating or removing a resource using the generic ARM cmdlets, the API version of the spec isn't supported by the corresponding service, so we need to give users a way to specify the API version that would like to use for the operation.

The idea is to add an optional `-ApiVersion` parameter that has a default value of the spec's defined API version to start with, and later we can discuss implementing a behavior that identifies the provider namespace and resource type and can grab the latest API version for that resource as the default.

**Comment by fearthecowboy** [comment]
@cormacpayne  -- try this out -- it will alter the `api-version` parameter on the three operations, and then tweak the name of the parameter back and fix the serialized name. 
 
``` yaml
directive:
  - from: swagger-document
    where: $..[?( /Resources_(CreateOrUpdate|Update|Delete)/g.exec(@.operationId))]
    transform: "$.parameters = $.parameters.map( each => { each.name = each.name === 'api-version' ? 'explicit-api-version' : each.name; return each; } );"
  - from: source-file-csharp
    where: $
    transform: $ = $.replace(/explicit-api-version/g, 'api-version');
  - where:
      parameter-name: ExplicitApiVersion
    set:
      parameter-name: ApiVersion    
```
