### ISSUE TITLE
Two properties of ExpressRouteCircuitConnection with the same name break build

### ISSUE THREAD

**Issue by number213** [Azure/autorest.powershell#448]
I've pulled the recent changes from `generation` branch and newly generate code doesn'; compile because there are two generated properties with the same name

```
generated\cmdlets\NewAzExpressRouteCircuitConnection_CreateViaIdentityExpanded.cs(85,23): error CS0102: The type 'NewAzExpressRouteCircuitConnection_CreateViaIdentityExpanded' already contains a definition for 'CircuitPeeringId' [D:\azure-powershell\src\Network\Az.Network.csproj]
generated\cmdlets\NewAzExpressRouteCircuitConnection_CreateExpanded.cs(99,23): error CS0102: The type 'NewAzExpressRouteCircuitConnection_CreateExpanded' already contains a definition for 'CircuitPeeringId' [D:\azure-powershell\src\Network\Az.Network.csproj]
generated\cmdlets\SetAzExpressRouteCircuitConnection_UpdateExpanded.cs(99,23): error CS0102: The type 'SetAzExpressRouteCircuitConnection_UpdateExpanded' already contains a definition for 'CircuitPeeringId' [D:\azure-powershell\src\Network\Az.Network.csproj]
D:\azure-powershell\src\Network\build-module.ps1 : Compilation failed.
```

This part of readme might be the case
```
  - where:
      subject: ExpressRouteCircuitConnection
      parameter-name: ^ExpressRouteCircuitPeeringId$|^PeerExpressRouteCircuitPeeringId$
    set:
      parameter-name: CircuitPeeringId
```
