### ISSUE TITLE
Allow parent descriptions to be merged with child descriptions when expanding

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.powershell#452]
For example:
```md
### -ExpressRouteCircuitPeeringId
Resource ID.
```

So, why does it just say `Resource ID.`? That's because this is an inherited property from SubResource. And, since that is a generic schema, the description is simple. The problem is that is the description written as the parameter for the cmdlet, which gives no context. There is a better description for the parameter:
```yaml
"expressRouteCircuitPeering": {
 "$ref": "./network.json#/definitions/SubResource",
 "description": "Reference to Express Route Circuit Private Peering Resource of the circuit initiating connection."
 },
```

As you can see, this is the actual parent's description to the `Id` property. Meaning, the **real description** of the parameter. Since there is no way to contextually tell if you want the child or parent's description, my solution is to combine both of them. So, in this case, you'd get:
```md
### -ExpressRouteCircuitPeeringId
Reference to Express Route Circuit Private Peering Resource of the circuit initiating connection.
Resource ID.
```

Thus, giving you context on what the actual parameter means. It would simply be parent description, then carriage return, then child description. I think this is a reasonable solution.
