### ISSUE TITLE
Configuration to suppress specific parameter expansion

### ISSUE THREAD

**Issue by MiYanni** [Azure/autorest.powershell#466]
In certain situations, it makes sense to not expand a specific parameter for a cmdlet. We should allow a way (directive) to specify a parameter should not get expanded. For example:

```yaml
  - where:
      subject: RecordSet
      parameter-name: SoaRecord
    do-not-expand: true
```

The only problem is, the only way to know what the parameter name that you don't want to expand is by either inferring it by the expanded parameter names (if they aren't reduced) or looking through the model property hierarchy and figuring out the name that way. It could be complex given the situation.
