### ISSUE TITLE
Specify no-inline on ALL schemas

### ISSUE THREAD

**Issue by brianwp3000** [Azure/autorest.powershell#743]
My service sends response objects like this:
```json
{
  "code": 200,
  "status": "OK",
  "data": {
    "FileName": "gameserver.zip",
    "AssetUploadUrl": "https://example.com"
  }
}
```
which Autorest.Powershell then flattens into this:
```json
{
  "code": 200,
  "status": "OK",
  "dataFileName": "gameserver.zip",
  "dataAssetUploadUrl": "https://example.com"
}
```
I can prevent this flattening behavior on that response object with the following directive:
```yaml
directives:
  - no-inline:
    - MyResponseSchema
```

I want to prevent ALL my schemas from being flattened like this--is there a way to do that? I tried the following (and several other similar directives) but can't get it to work:
```yaml
directives:
  - no-inline:
    - (.*)
```
