### ISSUE TITLE
Feature request: Provide a way to alias commands in bulk

### ISSUE THREAD

**Issue by peombwa** [Azure/autorest.powershell#769]
Currently, one can only alias commands one at a time by selecting a command's verb and/or subject, see https://github.com/Azure/autorest.powershell/blob/master/docs/directives.md#cmdlet-aliasing.

#### Option 1
Allow `alias:` have access to the match group of a `subject:` e.g.:
``` yml
  - where:
      subject: (.*)(WindowsUpdates)(.*)
    set:
      alias: ${verb}-Mg$1WU$3
```
#### Option 2
Add a rename directive for alias e.g.
``` yml
  - where:
      alias: Get-(.*)WindowsUpdates(.*)
    set:
      alias: Get-$1WU$3
```

**Comment by dolauli** [comment]
Following is how we support to alias command in bulk.
```  
- where:
      subject: (.*)(WindowsUpdates)(.*)
    set:
      alias: ${verb}-Mg${subject-prefix}${subject}xxx
```
If {verb}, {subject-prefix}, {subject} is specified in alias, they will be replaced accordingly. And the other part will be kept unchanged.
