### ISSUE TITLE
There is no any error or hint when module name cannot be found

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/autorest.powershell#844]
There is no any error or hint when module name cannot be found in below configuration.

```
  - where:
      module-name: NonExisting
    set:
      format-table:
        properties:
          - DisplayName
          - Id
          - Mail
```
