### ISSUE TITLE
resourcegroup-append can not work correctly with format-table

### ISSUE THREAD

**Issue by dolauli** [Azure/autorest.powershell#886]
There are two issues.
1.  ResourceGroupName is always printed out even it is not specified in format-table for a model. In following case,  ResourceGroupName is not set, but it still appears in table view.
``` 
  - where:
      model-name: Workspace
    set:
      format-table:
        properties:
          - Name
          - Location
          - ManagedResourceGroupId
        labels:
          ManagedResourceGroupId: Managed Resource Group ID
```
2.  ResourceGroupName always appear in the last column in table view. In following case, ResourceGroupName is set in column#3, but actually it will appear in the last column
``` 
  - where:
      model-name: Workspace
    set:
      format-table:
        properties:
          - Name
          - Location
          - ResourceGroupName 
          - ManagedResourceGroupId
        labels:
          ManagedResourceGroupId: Managed Resource Group ID
```
