### ISSUE TITLE
codegenerator cannot generate code for a return object - how to debug

### ISSUE THREAD

**Issue by Jawz84** [Azure/autorest.powershell#96]
After I have generated a PowerShell module, my cmdlet fails with 'reference not set to an instance of an object'. After much digging, I found that the codegenerator cannot generate the right code for my return object:

```c#
await onOK(_response,null /* deserializeFromResponse doesn't support '-none-' C:\Users\Jos.Koelewijn\.autorest\@microsoft.azure_autorest.csharp-v2@1.0.157\node_modules\@microsoft.azure\autorest.csharp-v2\dist\schema\object.js*/);                       
```

My return object is defined in yaml as follows:
 
```yaml
definitions:
  Model0:
    properties:
      system_id:
        type: integer
        format: Int32
      modules:
        type: integer
        format: Int32
      size_w:
        type: integer
        format: Int32
      current_power:
        type: integer
        format: Int32
      energy_today:
        type: integer
        format: Int32
      energy_lifetime:
        type: integer
        format: Int32
      summary_date:
        type: string
      source:
        type: string
      status:
        type: string
      operational_at:
        type: integer
        format: UnixTime
      last_report_at:
        type: integer
        format: UnixTime
      last_interval_end_at:
        type: integer
        format: UnixTime
```
no errors during code generation:
```text
~\Desktop> autorest.cmd  --powershell --input-file=.\openapi.yaml
AutoRest code generation utility [version: 3.0.5155; node: v10.15.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\Jos.Koelewijn\.autorest\@microsoft.azure_autorest-core@3.0.5386\node_modules\@microsoft.azure\autorest-core\dist' (3.0.5386)
   Loading AutoRest extension '@microsoft.azure/autorest.powershell' (beta->1.0.220)
   Loading AutoRest extension '@microsoft.azure/autorest.remodeler' (beta->1.0.144)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp-v2' (beta->1.0.157)
--------------------------------------------------------------------

WARNING (UndefinedTypeWithSchema): The schema 'schemas:4' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'
    - oai3-subset-schema-reduced doc... ($)
```

I would love to find out how to troubleshoot this on my own, but i'll need some guidance.
